name: Daily Portia Digest

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run daily digest
      env:
        PORTIA_API_KEY: ${{ secrets.PORTIA_API_KEY }}
        PORTIA_ORG_ID: ${{ secrets.PORTIA_ORG_ID }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GMAIL_TO: ${{ secrets.GMAIL_TO }}
        DIGEST_SUBJECT_PREFIX: ${{ secrets.DIGEST_SUBJECT_PREFIX }}
      run: |
        python -m portia_fetch.cli digest --yesterday --with-tools
    
    - name: Upload results (if any)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: digest-results
        path: |
          analysis_*.json
          summary_*.txt
          body_*.txt
        retention-days: 7
